_BASE_: "Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True
  #WEIGHTS: "fast-reid/checkpoints/market_sbs_R101-ibn.pth"
  WEIGHTS: "../fast-reid/checkpoints/market_sbs_R101-ibn.pth"

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/sbs_R101-ibn"
